# Generated by Django 2.2.8 on 2019-12-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
