# Generated by Django 2.2.8 on 2019-12-07 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0004_auto_20191207_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pole.Pole')),
            ],
        ),
    ]
