# Generated by Django 2.2.8 on 2019-12-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0005_poleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
