# Generated by Django 2.2.8 on 2019-12-08 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0006_pole_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poleimage',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pole.Pole'),
        ),
    ]
